require "pry"
require "rspec"
#require_relative "../lib/blackjack"
require_relative "../lib/card"
require_relative "../lib/deck"
require_relative "../lib/hand"
# require_relative "deck"
# require_relative "hand"
